/* 
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITESRIGHTS ARE FOR WHITES
 * RIGHTS ARE FOR WHITES









 */


